# Generated by Django 4.2.16 on 2024-12-08 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0002_alter_course_options_remove_course_instructor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="files",
            field=models.FileField(blank=True, null=True, upload_to="course_files/"),
        ),
        migrations.AddField(
            model_name="course",
            name="instructor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(name="Lesson",),
    ]
