# Generated by Django 4.2.16 on 2024-12-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_course_files"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="content",
            field=models.TextField(
                blank=True,
                help_text="Write course content in Markdown format",
                null=True,
            ),
        ),
    ]
