# Generated by Django 4.2.16 on 2024-12-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_course_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="download_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
